'use client';
import { useEffect, useState } from 'react';
import { books } from '@/data/books';
import { genesis, quiz, QuizQuestion } from '@/data/genesis';
import { AppState, defaultState, loadState, saveState, scheduleReview } from '@/lib/storage';
import ServiceWorker from './ServiceWorker';
import { cloudConfigured, getCloudUser, loadCloudState, onCloudAuthChange, recordCloudAnswer, recordExplanationAttempt, requestMagicLink, saveCloudState, signOutCloud } from '@/lib/cloud';
type View='home'|'books'|'genesis'|'learn'|'train'|'review'|'explain'|'sixty';
const nav:{key:View;label:string}[]=[{key:'home',label:'Início'},{key:'books',label:'66 livros'},{key:'genesis',label:'Gênesis'},{key:'review',label:'Revisar'}];
function norm(s:string){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-').replace(/\s+/g,' ').trim()}
function scoreText(value:string,answer:string){const parts=answer.split('|').map(norm),v=norm(value);const hits=parts.filter(p=>v.includes(p)).length;return{correct:hits===parts.length,partial:hits>0&&hits<parts.length}}
function mastery(s:AppState){if(!s.attempts.length)return 0;return Math.round(100*s.attempts.filter(a=>a.correct).length/s.attempts.length)}
function shuffle<T>(a:T[]){return[...a].sort(()=>Math.random()-.5)}
export default function BibleApp(){
const[view,setView]=useState<View>('home'),[state,setState]=useState<AppState>(defaultState),[ready,setReady]=useState(false),[learnShow,setLearnShow]=useState(false),[sessionPool,setSessionPool]=useState<string[]>(quiz.map(q=>q.id)),[trainIdx,setTrainIdx]=useState(0),[trainValue,setTrainValue]=useState(''),[order,setOrder]=useState<string[]>([]),[result,setResult]=useState<null|'correct'|'partial'|'wrong'>(null),[authEmail,setAuthEmail]=useState(''),[authOpen,setAuthOpen]=useState(false),[authMessage,setAuthMessage]=useState(''),[cloudUser,setCloudUser]=useState<string|null>(null),[savingExplanation,setSavingExplanation]=useState(false),[sixtyIdx,setSixtyIdx]=useState(0),[sec,setSec]=useState(60),[running,setRunning]=useState(false);
useEffect(()=>{let s=loadState();if(!s.seededWeakPoint){s={...s,weakPoints:{...s.weakPoints,'Estrutura 1–11 / 12–50':1},seededWeakPoint:true};saveState(s)}setState(s);setReady(true);getCloudUser().then(u=>setCloudUser(u?.email||u?.id||null)).catch(()=>{});loadCloudState().then(cloud=>{if(!cloud)return;const lt=s.lastActivity?new Date(s.lastActivity).getTime():0,ct=cloud.lastActivity?new Date(cloud.lastActivity).getTime():0;if(ct>lt)setState(cloud)}).catch(()=>{});const off=onCloudAuthChange(()=>{getCloudUser().then(u=>setCloudUser(u?.email||u?.id||null)).catch(()=>{});loadCloudState().then(cloud=>{if(cloud)setState(cloud)}).catch(()=>{})});return off},[]);
useEffect(()=>{if(!ready)return;saveState(state);const t=setTimeout(()=>{saveCloudState(state).catch(()=>{})},450);return()=>clearTimeout(t)},[state,ready]);
useEffect(()=>{if(view!=='sixty'||!running||sec<=0)return;const t=setTimeout(()=>setSec(s=>s-1),1000);return()=>clearTimeout(t)},[view,running,sec]);
const precision=mastery(state),weak=Object.entries(state.weakPoints).sort((a,b)=>b[1]-a[1]),due=state.nextReview?new Date(state.nextReview)<=new Date():weak.length>0,currentQuestion=quiz.find(q=>q.id===sessionPool[trainIdx])||quiz[0];
function go(v:View){setView(v);window.scrollTo({top:0,behavior:'smooth'})}
function prepareQuestion(q:QuizQuestion){setTrainValue('');setResult(null);setOrder(q.type==='order'?shuffle(q.answer as string[]):[])}
function startTraining(mode:'train'|'review'){let pool=quiz;if(mode==='review'&&weak.length){const f=quiz.filter(q=>weak.some(([w])=>w===q.concept));if(f.length)pool=f}setSessionPool(pool.map(q=>q.id));setTrainIdx(0);prepareQuestion(pool[0]);go(mode)}
function submitAnswer(selected?:string){const q=currentQuestion,val=q.type==='order'?order:(selected??trainValue);let correct=false,partial=false;if(q.type==='text'){const s=scoreText(String(val),q.answer as string);correct=s.correct;partial=s.partial}else if(q.type==='choice')correct=val===q.answer;else correct=JSON.stringify(order)===JSON.stringify(q.answer);setResult(correct?'correct':partial?'partial':'wrong');setState(s=>{const wp={...s.weakPoints},delta=correct?-1:partial?1:2;wp[q.concept]=Math.max(0,(wp[q.concept]||0)+delta);if(wp[q.concept]===0)delete wp[q.concept];return{...s,attempts:[...s.attempts,{questionId:q.id,concept:q.concept,correct,partial,answer:val,at:new Date().toISOString()}],weakPoints:wp,lastActivity:new Date().toISOString(),nextReview:scheduleReview(correct,0)}});recordCloudAnswer({questionId:q.id,answer:val,correct,partial}).catch(()=>{})}
function nextQuestion(){const n=(trainIdx+1)%sessionPool.length;setTrainIdx(n);prepareQuestion(quiz.find(x=>x.id===sessionPool[n])||quiz[0])}
function moveOrder(i:number,d:number){const j=i+d;if(j<0||j>=order.length)return;const c=[...order];[c[i],c[j]]=[c[j],c[i]];setOrder(c)}
function Home(){return <section className="stack"><div className="eyebrow">TRILHA INICIAL</div><h1>Dominando os 66 Livros</h1><p className="lead">Aprenda em camadas. Recupere da memória. Revise o que realmente esquece.</p><button className="heroCard" onClick={()=>go('learn')}><span className="kicker">CONTINUE SEU ESTUDO</span><strong>Gênesis</strong><span>Nível 1 · Localização e identidade</span><div className="bar"><i style={{width:`${Math.max(precision,18)}%`}}/></div><b>Continuar treinamento →</b></button><div className="metrics"><article><small>Domínio atual</small><strong>{precision}%</strong><span>baseado em recuperação</span></article><article><small>Revisão hoje</small><strong>{due?Math.max(weak.length,1):0}</strong><span>{due?'pontos para reforçar':'em dia'}</span></article></div>{weak[0]&&<button className="weak" onClick={()=>startTraining('review')}><span>PRECISA REFORÇAR</span><b>{weak[0][0]}</b><small>Esse ponto reaparecerá com maior frequência.</small></button>}<section className="section"><div className="sectionHead"><h2>Mapa da jornada</h2><button onClick={()=>go('books')}>Ver 66 livros</button></div><div className="testament"><div><b>Antigo Testamento</b><span>39 livros</span></div><div><b>Novo Testamento</b><span>27 livros</span></div></div></section><section className="today"><h2>Hoje · 12–15 min</h2><button onClick={()=>go('learn')}><b>Aprender</b><span>Gênesis · microblocos</span><em>5 min</em></button><button onClick={()=>startTraining('review')}><b>Recuperar</b><span>Pontos frágeis</span><em>4 min</em></button><button onClick={()=>{setSec(60);setSixtyIdx(0);setRunning(false);go('sixty')}}><b>60 segundos</b><span>Revisão rápida</span><em>1 min</em></button><button onClick={()=>go('explain')}><b>Explicar</b><span>Com suas palavras</span><em>2 min</em></button></section></section>}
function Books(){const groups=[...new Set(books.map(b=>`${b.testament}|${b.division}`))];return <section className="stack"><div className="eyebrow">MAPA CANÔNICO</div><h1>66 livros</h1><p className="lead">Veja onde cada livro está antes de aprofundar seu conteúdo.</p>{groups.map(g=>{const[t,d]=g.split('|'),list=books.filter(b=>b.testament===t&&b.division===d);return <section className="bookGroup" key={g}><div className="sectionHead"><h2>{d}</h2><span>{list.length}</span></div><div className="bookGrid">{list.map(b=><button key={b.id} className={b.id===1?'book activeBook':'book'} onClick={()=>b.id===1&&go('genesis')}><small>{String(b.id).padStart(2,'0')}</small><b>{b.name}</b><span>{b.id===1?'Em aprendizagem':'Não iniciado'}</span></button>)}</div></section>})}</section>}
function Genesis(){return <section className="stack"><div className="genHero"><div className="sun"/><div className="crack"/><div className="sprout">✦</div><span>IMAGEM-ÂNCORA CONCEITUAL</span><h1>Gênesis</h1><p>Começo, queda e promessa.</p></div><div className="chips">{genesis.identity.map(x=><span key={x}>{x}</span>)}</div><section className="section"><div className="eyebrow">GPS BÍBLICO</div><div className="gps">Antigo Testamento <b>→</b> Pentateuco <b>→</b> Gênesis <b>→</b> Livro 1/66</div></section><section className="section"><h2>Estrutura mental</h2><div className="twoCols">{genesis.blocks.map(b=><article key={b.range}><small>GÊNESIS {b.range}</small><strong>{b.title}</strong><p>{b.items.join(' · ')}</p></article>)}</div></section><section className="section"><h2>Pessoas-âncora</h2><div className="people">{genesis.people.map(([n,a],i)=><article key={n}><span>{i+1}</span><div><b>{n}</b><small>{a}</small></div></article>)}</div></section><section className="section"><h2>Linha do tempo</h2><div className="timeline">{genesis.timeline.map(x=><span key={x}>{x}</span>)}</div></section><section className="section"><h2>Leia na Bíblia</h2>{genesis.reading.map(([r,d])=><div className="reading" key={r}><b>{r}</b><span>{d}</span></div>)}</section><div className="actions"><button className="primary" onClick={()=>go('learn')}>Aprender Nível 1</button><button onClick={()=>startTraining('train')}>Treinar agora</button><button onClick={()=>{setSec(60);setSixtyIdx(0);setRunning(false);go('sixty')}}>Gênesis em 60s</button><button onClick={()=>go('explain')}>Explicar com minhas palavras</button></div></section>}
function Learn(){const cards=[{t:'Localização',h:'Gênesis abre a Bíblia',p:'Antigo Testamento · Pentateuco · Livro 1/66 · 50 capítulos',q:'Qual é a divisão de Gênesis?',a:'Pentateuco'},{t:'Estrutura',h:'Dois grandes blocos',p:'1–11 = Humanidade · 12–50 = Família da promessa',q:'Onde começam os patriarcas?',a:'Capítulo 12'},{t:'Personagens',h:'Uma corrente de memória',p:'Adão e Eva → Noé → Abraão → Isaque → Jacó → José',q:'Quem vem depois de Isaque?',a:'Jacó'},{t:'História da redenção',h:'Três palavras',p:'Criação → Queda → Promessa',q:'O que vem depois da Queda?',a:'Promessa'},{t:'Conexão',h:'Gênesis prepara Êxodo',p:'A família de Jacó termina no Egito. Êxodo retoma seus descendentes já numerosos e oprimidos.',q:'Onde a família está ao final de Gênesis?',a:'Egito'}],c=cards[Math.min(state.learnStep,cards.length-1)],done=state.learnStep>=cards.length-1&&learnShow;return <section className="lesson"><button className="back" onClick={()=>go('genesis')}>← Gênesis</button><div className="lessonProgress"><i style={{width:`${((state.learnStep+1)/cards.length)*100}%`}}/></div><span className="eyebrow">{c.t}</span><h1>{c.h}</h1><p className="learnText">{c.p}</p><div className="recall"><small>SEM VOLTAR</small><b>{c.q}</b>{!learnShow?<button className="primary" onClick={()=>setLearnShow(true)}>Mostrar resposta</button>:<><strong>{c.a}</strong><p>Recupere primeiro; confira depois. É esse esforço que fortalece a memória.</p></>}</div>{learnShow&&<button className="next" onClick={()=>{if(done)startTraining('train');else{setState(s=>({...s,learnStep:s.learnStep+1,lastActivity:new Date().toISOString()}));setLearnShow(false)}}}>{done?'Ir para treinamento →':'Próximo microbloco →'}</button>}</section>}
function Train(){const q=currentQuestion;return <section className="lesson"><button className="back" onClick={()=>go('genesis')}>← Gênesis</button><div className="eyebrow">{view==='review'?'REVISÃO ADAPTATIVA':'TREINAMENTO'}</div><div className="trainMeta"><span>{q.concept}</span><b>{trainIdx+1}/{sessionPool.length}</b></div><h1 className="question">{q.prompt}</h1>{q.type==='choice'&&<div className="choices">{q.options!.map(o=><button disabled={result!==null} onClick={()=>{setTrainValue(o);submitAnswer(o)}} key={o}>{o}</button>)}</div>}{q.type==='text'&&<div className="textAnswer"><input disabled={result!==null} value={trainValue} onChange={e=>setTrainValue(e.target.value)} placeholder="Digite com suas palavras"/><button className="primary" disabled={!trainValue||result!==null} onClick={()=>submitAnswer()}>Responder</button></div>}{q.type==='order'&&<div><div className="order">{order.map((o,i)=><div className="orderRow" key={`${o}-${i}`}><span>{i+1}. {o}</span><button disabled={result!==null||i===0} onClick={()=>moveOrder(i,-1)}>↑</button><button disabled={result!==null||i===order.length-1} onClick={()=>moveOrder(i,1)}>↓</button></div>)}</div><button className="primary" disabled={result!==null} onClick={()=>submitAnswer()}>Confirmar ordem</button></div>}{result!==null&&<div className={result==='correct'?'feedback ok':result==='partial'?'feedback partial':'feedback no'}><b>{result==='correct'?'Correto':result==='partial'?'Parcialmente correto':'Reforçar'}</b><p>{q.explanation}</p><button onClick={nextQuestion}>Próxima pergunta →</button></div>}</section>}
function Explain(){const text=state.explanation,concepts=[['primeiro livro',['primeiro livro','livro 1']],['Pentateuco',['pentateuco']],['1–11 humanidade',['1-11','1 a 11','humanidade']],['12–50 família da promessa',['12-50','12 a 50','familia da promessa']],['criação',['criacao']],['queda',['queda']],['promessa',['promessa']],['Abraão',['abraao']],['Isaque',['isaque']],['Jacó',['jaco']],['José',['jose']],['Egito',['egito']]] as const,found=concepts.filter(([,terms])=>terms.some(t=>norm(text).includes(norm(t)))),foundNames=new Set(found.map(c=>c[0])),missing=concepts.filter(c=>!foundNames.has(c[0]));return <section className="stack"><button className="back" onClick={()=>go('genesis')}>← Gênesis</button><div className="eyebrow">NÍVEL 4 · ENSINO</div><h1>Explique com suas palavras</h1><p className="lead">Explique Gênesis em aproximadamente 60 segundos.</p><textarea value={text} onChange={e=>setState(s=>({...s,explanation:e.target.value,lastActivity:new Date().toISOString()}))} placeholder="Gênesis é..." rows={9}/><div className="explainGrid"><article><small>CONCEITOS RECUPERADOS</small><strong>{found.length}/12</strong>{found.map(c=><span key={c[0]}>✓ {c[0]}</span>)}</article><article><small>PONTOS PARA REFORÇAR</small>{missing.map(c=><span key={c[0]}>· {c[0]}</span>)}</article></div><button className="primary" disabled={!text.trim()||savingExplanation} onClick={async()=>{setSavingExplanation(true);await recordExplanationAttempt({text,recovered:found.map(c=>c[0]),missing:missing.map(c=>c[0])});setSavingExplanation(false)}}>{savingExplanation?'Salvando…':'Salvar esta tentativa'}</button></section>}
function AuthPanel(){if(!cloudConfigured())return null;if(cloudUser)return <div className="authPanel"><small>Sincronização em nuvem ativa</small><b>{cloudUser}</b><button onClick={async()=>{await signOutCloud();setCloudUser(null)}}>Sair</button></div>;return <div className="authPanel"><small>SINCRONIZE ENTRE DISPOSITIVOS</small><b>Entrar por e-mail</b><p>Receba um link seguro no seu e-mail. Não é necessário criar senha.</p><input type="email" value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="seu@email.com"/><button className="primary" disabled={!authEmail.includes('@')} onClick={async()=>{const r=await requestMagicLink(authEmail);setAuthMessage(r.message)}}>Enviar link de acesso</button>{authMessage&&<p>{authMessage}</p>}</div>}
function Sixty(){const prompts=['Posição?','Divisão?','1–11?','12–50?','Personagens-âncora?','História da redenção?','Frase-âncora?','Onde termina?'];return <section className="sixty"><button className="back" onClick={()=>go('genesis')}>← Gênesis</button><span className="timer">{sec}s</span><div className="eyebrow">RECUPERAÇÃO RÁPIDA</div><h1>{prompts[sixtyIdx]}</h1><p>Responda mentalmente antes de avançar.</p>{!running?<button className="primary" onClick={()=>setRunning(true)}>Iniciar 60 segundos</button>:<button className="primary" disabled={sec<=0} onClick={()=>setSixtyIdx(x=>(x+1)%prompts.length)}>{sec<=0?'Tempo encerrado':'Próximo estímulo →'}</button>}</section>}
return <><ServiceWorker/><div className="shell"><header className="top"><button className="brand" onClick={()=>go('home')}><span className="brandmark">BV</span><span><b>Bíblia Viva</b><small>Conheça · Entenda · Memorize · Conecte</small></span></button><button className="sync" onClick={()=>cloudConfigured()&&setAuthOpen(x=>!x)}>{!cloudConfigured()?'MVP local':cloudUser?'Sincronizado':'Entrar'}</button></header>{authOpen&&<AuthPanel/>}<main>{view==='home'&&<Home/>}{view==='books'&&<Books/>}{view==='genesis'&&<Genesis/>}{view==='learn'&&<Learn/>}{(view==='train'||view==='review')&&<Train/>}{view==='explain'&&<Explain/>}{view==='sixty'&&<Sixty/>}</main><nav className="bottom">{nav.map(n=><button key={n.key} className={view===n.key?'active':''} onClick={()=>n.key==='review'?startTraining('review'):go(n.key)}>{n.label}</button>)}</nav></div></>}
