'use client';
import type { AppState } from './storage'; import { createSupabaseBrowserClient } from './supabase';
let client:ReturnType<typeof createSupabaseBrowserClient>|undefined; function getClient(){if(client===undefined)client=createSupabaseBrowserClient();return client}
export function cloudConfigured(){return!!getClient()}
export async function getCloudUser(){const s=getClient();if(!s)return null;const{data:{session}}=await s.auth.getSession();return session?.user??null}
export async function requestMagicLink(email:string){const s=getClient();if(!s)return{ok:false,message:'Supabase ainda não está configurado.'};const redirectTo=typeof window!=='undefined'?window.location.origin:undefined;const{error}=await s.auth.signInWithOtp({email,options:redirectTo?{emailRedirectTo:redirectTo}:undefined});return error?{ok:false,message:error.message}:{ok:true,message:'Enviamos um link de acesso para seu e-mail.'}}
export async function signOutCloud(){const s=getClient();if(s)await s.auth.signOut()}
export function onCloudAuthChange(cb:()=>void){const s=getClient();if(!s)return()=>{};const{data}=s.auth.onAuthStateChange(()=>cb());return()=>data.subscription.unsubscribe()}
export async function loadCloudState():Promise<AppState|null>{const s=getClient(),u=await getCloudUser();if(!s||!u)return null;const{data,error}=await s.from('user_progress').select('*').eq('user_id',u.id).maybeSingle();if(error||!data)return null;return{currentBook:data.current_book,currentLevel:data.current_level,learnStep:data.learn_step,attempts:data.attempts||[],weakPoints:data.weak_points||{},lastActivity:data.last_activity,nextReview:data.next_review,explanation:data.explanation||'',seededWeakPoint:true}}
export async function saveCloudState(st:AppState){const s=getClient(),u=await getCloudUser();if(!s||!u)return false;const correct=st.attempts.filter(a=>a.correct).length,mastery=st.attempts.length?Math.round(100*correct/st.attempts.length):0;const{error}=await s.from('user_progress').upsert({user_id:u.id,current_book:st.currentBook,current_level:st.currentLevel,learn_step:st.learnStep,attempts:st.attempts,weak_points:st.weakPoints,explanation:st.explanation,next_review:st.nextReview,last_activity:st.lastActivity,updated_at:new Date().toISOString()});if(error)return false;await s.from('user_book_progress').upsert({user_id:u.id,book_id:st.currentBook,current_level:st.currentLevel,mastery,status:mastery>=90?'level_1_complete':'learning',updated_at:new Date().toISOString()});return true}
export async function recordCloudAnswer(input:{questionId:string;answer:unknown;correct:boolean;partial:boolean}){const s=getClient(),u=await getCloudUser();if(!s||!u)return false;const{error}=await s.from('user_answers').insert({user_id:u.id,question_id:input.questionId,answer:input.answer,correct:input.correct,partial:input.partial});return!error}
export async function recordExplanationAttempt(input:{text:string;recovered:string[];missing:string[]}){const s=getClient(),u=await getCloudUser();if(!s||!u)return false;const{error}=await s.from('explanation_attempts').insert({user_id:u.id,book_id:1,level_number:1,response_text:input.text,recovered_concepts:input.recovered,missing_concepts:input.missing});return!error}